In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression


In [62]:
data=pd.read_csv('Iris.csv')
data.head(120)

sepal length  sepal width  petal length  petal width             iris  \
0             5.1          3.5           1.4          0.2      Iris-setosa   
1             4.9          3.0           1.4          0.2      Iris-setosa   
2             4.7          3.2           1.3          0.2      Iris-setosa   
3             4.6          3.1           1.5          0.2      Iris-setosa   
4             5.0          3.6           1.4          0.2      Iris-setosa   
5             5.4          3.9           1.7          0.4      Iris-setosa   
6             4.6          3.4           1.4          0.3      Iris-setosa   
7             5.0          3.4           1.5          0.2      Iris-setosa   
8             4.4          2.9           1.4          0.2      Iris-setosa   
9             4.9          3.1           1.5          0.1      Iris-setosa   
10            5.4          3.7           1.5          0.2      Iris-setosa   
11            4.8          3.4           1.6          0.2      Iris-setosa   
12            4.8          3.0           1.4          0.1      Iris-setosa   
13            4.3          3.0           1.1          0.1      Iris-setosa   
14            5.8          4.0           1.2          0.2      Iris-setosa   
15            5.7          4.4           1.5          0.4      Iris-setosa   
16            5.4          3.9           1.3          0.4      Iris-setosa   
17            5.1          3.5           1.4          0.3      Iris-setosa   
18            5.7          3.8           1.7          0.3      Iris-setosa   
19            5.1          3.8           1.5          0.3      Iris-setosa   
20            5.4          3.4           1.7          0.2      Iris-setosa   
21            5.1          3.7           1.5          0.4      Iris-setosa   
22            4.6          3.6           1.0          0.2      Iris-setosa   
23            5.1          3.3           1.7          0.5      Iris-setosa   
24            4.8          3.4           1.9          0.2      Iris-setosa   
25            5.0          3.0           1.6          0.2      Iris-setosa   
26            5.0          3.4           1.6          0.4      Iris-setosa   
27            5.2          3.5           1.5          0.2      Iris-setosa   
28            5.2          3.4           1.4          0.2      Iris-setosa   
29            4.7          3.2           1.6          0.2      Iris-setosa   
..            ...          ...           ...          ...              ...   
90            5.5          2.6           4.4          1.2  Iris-versicolor   
91            6.1          3.0           4.6          1.4  Iris-versicolor   
92            5.8          2.6           4.0          1.2  Iris-versicolor   
93            5.0          2.3           3.3          1.0  Iris-versicolor   
94            5.6          2.7           4.2          1.3  Iris-versicolor   
95            5.7          3.0           4.2          1.2  Iris-versicolor   
96            5.7          2.9           4.2          1.3  Iris-versicolor   
97            6.2          2.9           4.3          1.3  Iris-versicolor   
98            5.1          2.5           3.0          1.1  Iris-versicolor   
99            5.7          2.8           4.1          1.3  Iris-versicolor   
100           6.3          3.3           6.0          2.5   Iris-virginica   
101           5.8          2.7           5.1          1.9   Iris-virginica   
102           7.1          3.0           5.9          2.1   Iris-virginica   
103           6.3          2.9           5.6          1.8   Iris-virginica   
104           6.5          3.0           5.8          2.2   Iris-virginica   
105           7.6          3.0           6.6          2.1   Iris-virginica   
106           4.9          2.5           4.5          1.7   Iris-virginica   
107           7.3          2.9           6.3          1.8   Iris-virginica   
108           6.7          2.5           5.8          1.8   Iris-virginica   
109           7.2          

In [32]:
#preprocessing the data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data['iris']=le.fit_transform(data['iris'])
data.head()
#for col in data.columns:
   # print(col)


sepal length  sepal width  petal length  petal width  iris  Unnamed: 5  \
0           5.1          3.5           1.4          0.2     0         NaN   
1           4.9          3.0           1.4          0.2     0         NaN   
2           4.7          3.2           1.3          0.2     0         NaN   
3           4.6          3.1           1.5          0.2     0         NaN   
4           5.0          3.6           1.4          0.2     0         NaN   

   Unnamed: 6  Unnamed: 7  Unnamed: 8  
0         NaN         NaN         NaN  
1         NaN         NaN         NaN  
2         NaN         NaN         NaN  
3         NaN         NaN         NaN  
4         NaN         NaN         NaN

In [40]:
#dropping all the unnecessary coloumns
x= np.array(data.drop(['Unnamed: 5','iris','Unnamed: 6','Unnamed: 7','Unnamed: 8'],axis=1))
y=np.array(data['iris'])

In [53]:
#training and testing set
x_train, x_test=x[20:],x[:20]
y_train, y_test=y[20:],y[:20]
x_train.shape , y_test.shape
y_train.shape , y_test.shape

((130,), (20,))

In [56]:
#building the model
f=LogisticRegression(solver='lbfgs',multi_class='auto')
f.fit(x,y)
w,b=f.coef_,f.intercept_
w,b

(array([[-0.42340128,  0.96171383, -2.51952248, -1.08592601],
        [ 0.53415829, -0.31797653, -0.20537738, -0.93967979],
        [-0.110757  , -0.6437373 ,  2.72489986,  2.0256058 ]]),
 array([  9.88127629,   2.21930928, -12.10058557]))

In [49]:
#accuracy of the model
accuracy=f.score(x,y)
print(accuracy*100)

96.0


In [70]:
probtrain=f.predict_proba(x_train)
probtrain[0:10]
probtest=f.predict(x_test)

In [71]:
probtest

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [72]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [78]:
plt.scatter(x_test[:,0], x_test[:,1],c=y_test)
ax=plt.gca()
xvalue=np.array(ax.get_xlim())
yvalue=-(xvalue*w[0][0]+b[0])/w[0][1]
plt.plot(xvalue,yvalue)

